### ISSUE TITLE
web: provide a useable login mechanism

### ISSUE THREAD

**Issue by scanf** [HiOA-ABI/nikita-noark5-core#45]
The current login setup is not really useable because of the redirect. @petterreinholdtsen said it was fixed, but from my testing (see below) there are still issues.. Please provide a more Javascript friendly way to login and some documentation so that it can be easily used. With the current setup not much progress can be had with the other endpoints when there is no way to be authenticated.

```javascript
  XMLHttpRequest cannot load http://127.0.0.1:8092/noark5v4/doLogin. Redirect
    from 'http://127.0.0.1:8092/noark5v4/doLogin' to
    'http://127.0.0.1:8092/noark5v4/login?error' has been blocked by CORS policy:
    No 'Access-Control-Allow-Origin' header is present on the requested resource.
    Origin 'http://localhost:3000' is therefore not allowed access.
```

**Comment by petterreinholdtsen** [comment]
[Alexander Alemayhu]
> The current login setup is not really useable because of the
> redirect. @petterreinholdtsen said it was fixed, but from my testing
> (see below) there are still issues.. Please provide a more Javascript
> friendly way to login and some documentation so that it can be easily
> used.

I suspect part of the problem is that we do not quite know what "a more
Javascript friendly way to login" should look like.  Do you have any
nice pointers explaining what you would prefer?

Is simple http authenticaion better?  What about SAML?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by scanf** [comment]
[RFC7519](https://tools.ietf.org/html/rfc7519)
>JSON Web Token (JWT) is a compact, URL-safe means of representing
   claims to be transferred between two parties.  The claims in a JWT
   are encoded as a JSON object that is used as the payload of a JSON
   Web Signature (JWS) structure or as the plaintext of a JSON Web
   Encryption (JWE) structure, enabling the claims to be digitally
   signed or integrity protected with a Message Authentication Code
   (MAC) and/or encrypted.

Maybe it can be used? See [Toptal blog post](https://www.toptal.com/java/rest-security-with-jwt-spring-security-and-java) for a spring related example.
![toptal info](https://uploads.toptal.io/blog/image/91979/toptal-blog-image-1453117846175-a2626bfb43844c939a12d57666ac2f90.jpg)

**Comment by tsodring** [comment]
Thanks. The toptal blogpost has a concrete example that I can work of. I'll give it a go and see what I can get done.

**Comment by scanf** [comment]
Will test this and update soon.

**Comment by scanf** [comment]
@tsodring Awesome work.
