### ISSUE TITLE
Respons from POST to ny-arkivskaper is missing ny-arkiv relation.

### ISSUE THREAD

**Issue by petterreinholdtsen** [HiOA-ABI/nikita-noark5-core#65]
I expected to be able to create a fonds belonging to a freshly created record creator, but there is no http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-arkiv/ relation in the response.

**Comment by tsodring** [comment]
Hi Petter,

I'm a little unsure how to recreate the issue. When I run the following curl request:

curl -v -s --header Accept:application/vnd.noark5-v4+json --header Authorization:AUTH_CODE --header Content-Type:application/vnd.noark5-v4+json -X POST --data @./json-example-data/fonds-creator-data.json http://localhost:8092/noark5v4/hateoas-api/arkivstruktur/ny-arkivskaper

I get the following result:

{
  "systemID" : "7d86149b-a8b5-4b15-8f9d-cc9e0ac346a3",
  "arkivskaperID" : "123456789",
  "arkivskaperNavn" : "Eksempel kommune",
  "beskrivelse" : "Eksempel kommune ligger i eksempel fylke nord for nord",
  "_links" : [ {
    "href" : "http://localhost:8092/noark5v4/hateoas-api/arkivstruktur/arkivskaper/7d86149b-a8b5-4b15-8f9d-cc9e0ac346a3/",
    "rel" : "self",
    "templated" : false
  }, {
    "href" : "http://localhost:8092/noark5v4/hateoas-api/arkivstruktur/arkiv/7d86149b-a8b5-4b15-8f9d-cc9e0ac346a3/arkiv/",
    "rel" : "http://rel.kxml.no/noark5/v4/api/arkivstruktur/arkiv/",
    "templated" : false
  }, {
    "href" : "http://localhost:8092/noark5v4/hateoas-api/arkivstruktur/arkivskaper/7d86149b-a8b5-4b15-8f9d-cc9e0ac346a3/ny-arkiv/",
    "rel" : "http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-arkiv/",
    "templated" : false
  } ]
}

Could you post a copy of the request to aid debugging?

**Comment by petterreinholdtsen** [comment]
Try running ./runtest; ./runtest --verbose on a blank database.  The second run will fail.

**Comment by tsodring** [comment]
After our discussions and the commit last night, I think this issue is closed. Agree?

**Comment by petterreinholdtsen** [comment]
[Thomas Sødring]
> After our discussions and the commit last night, I think this issue is
> closed. Agree?

Yes.

--
Happy hacking
Petter Reinholdtsen
