### ISSUE TITLE
OPTIONS request no longer work

### ISSUE THREAD

**Issue by petterreinholdtsen** [HiOA-ABI/nikita-noark5-core#66]
I suspect the problem was introduced around 26fae1c8a5588df097d2d392704512d9faef6976 ?

**Comment by tsodring** [comment]
I'm not sure. Will do some debugging. Although it's probably [this](https://github.com/HiOA-ABI/nikita-noark5-core/blob/master/core-webapp/src/main/java/no/arkivlab/hioa/nikita/webapp/spring/SecurityConfig.java#L73)  that's causing the problem. 

I believe adding a ` .antMatchers(HttpMethod.OPTIONS, "/").permitAll()` will fix it. I'll give it a go ...

**Comment by tsodring** [comment]
Adding `.antMatchers(HttpMethod.OPTIONS, "/").permitAll()` seems to have worked ...

success: level 0 CORS - HTTP OPTTIONS request worked

I'll commit it.
