### ISSUE TITLE
Document unofficial relations and change them to nikita ones

### ISSUE THREAD

**Issue by tsodring** [HiOA-ABI/nikita-noark5-core#73]
The interface standard is missing a definition for a lot of RELS. We have for these "unofficial" RELS just assumed that they exist and this causes a problem as the core is out of sync with the current interface standard and it gives an impression that the interface standard has come further than it has.

We need to hunt down unofficial RELS and convert them to nikita RELS

A nikita REL looks like:
    "rel" : "http://nikita.arkivlab.no/noark5/v4/login/rfc7519/"

An official REL looks like
    "rel" : "http://rel.kxml.no/noark5/v4/api/arkivstruktur/"

This task can be done by cross checking all _links against the interface document and just changing a constant value in core-common.

**Comment by tsodring** [comment]
pere provided the following method to do that:
"./runtest | grep well |awk '/failure/ { print $3}'|sort -u"

**Comment by petterreinholdtsen** [comment]
[Thomas Sødring]
> pere provided the following method to do that:
> "./runtest | grep well |awk '/failure/ { print $3}'|sort -u"

This is the list.

http://rel.kxml.no/noark5/v4/api/arkivstruktur/arvtager/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/avslutt-mappe/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/forfatter/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/forloeper/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/gradering/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/kassasjon/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-arvtager/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-forfatter/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-forloeper/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-gradering/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-kassasjon/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-klassereferanse/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-oppbevaringsted/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-oppbevaringsteder/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-referanseArkivdel/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-sekundaerklassifikasjon/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-skjerming/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-sletting/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-underarkiv/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-undermappe/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-utfoertKassasjon/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/oppbevaringsted/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/referanseArkivdel/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/referanseKlasse/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/sekundaerklassifikasjon/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/skjerming/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/sletting/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/undermappe/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/utfoertKassasjon/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/utvid-til-moetemappe/
http://rel.kxml.no/noark5/v4/api/arkivstruktur/utvid-til-saksmappe/

I suspect 'ny-underarkiv' should be 'ny-arkiv', 'ny-undermappe' should
be 'ny-mappe' and 'undermappe' should be 'mappe'.  What is the
relationship between 'sletting' and a DELETE HTTP request?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by tsodring** [comment]
Thanks for the list!

That's an interesting question and something I don't know if I have ever really managed to understand properly. 

7.2.1.20 Sletting covers deletion, page 152 on the interface standard has sletting but only talks about deleting documents. So I guess to delete a document we could use a HTTP DELETE request.

However the metadata catalog describes `sletting` for `dokumentbesrkivelse` and `arkivdel`. Which also means that you cannot delete a document unless it's associated with a `dokumentbeskrivelse`. And you can only delete the production versions of those documents. I'm not even sure what the rel for that is

   REL http://rel.kxml.no/noark5/v4/api/arkivstruktur/dokumentbeskrivelse/
   HREF [contextpath][api]/arkivstruktur/dokumentbeskrivelse/{systemID} DELETE ??

This will delete the document but not the metadata / arkivenhet

Now the standard says :

_Det skal finnes en tjeneste/funksjon for administrator for å opprette, redigere og slette arkivenheter (arkiv, arkivdel, klassifikasjonssystem, klasse, mappe, registrering, dokumentbeskrivelse og  dokumentobjekt) og tilknyttede metadata som går utover de generelle begrensningene i kapittel 6.1.
Slike registreringer skal logges._

So I guess it should be possible to DELETE entities, as long as it is logged ... But if I delete a saksmappe, then  have to delete all of its children. But there is some business logic here:

   6.1.17 Det skal ikke være mulig å slette en Mappe som er avsluttet
   6.1.18 Det skal ikke være mulig å slette en Saksmappe som inneholder eller har inneholdt Journalposter med status ekspedert, journalført eller arkivert

So I guess as long as something is finalised I am allowed to delete it! How do we distinguish between a DELETE request for "sletting av variant" and a general DELETE of a a dokumentbeskrivelse.

So I still think I am a little unsure how to implement this.

**Comment by petterreinholdtsen** [comment]
I've tried in commit 110fb02571c2d74fe1e8704d21230c699aa95b03 to change all unofficial relations to use the http://nikita.arkivlab.no/noark5/v4/ prefix.

**Comment by petterreinholdtsen** [comment]
As far as I can tell, all official looking relations are now listed in the spec.
