### ISSUE TITLE
Ordering of results

### ISSUE THREAD

**Issue by tsodring** [HiOA-ABI/nikita-noark5-core#79]
Currently _links are in random order because we use a Set. Implementing a TreeSet fixes this. This should be further checked to ensure that all _links use a treeset so ordering is consistent

**Comment by petterreinholdtsen** [comment]
[Thomas Sødring]
> Currently _links are in random order because we use a
> Set. Implementing a TreeSet fixes this. This should be further checked
> to ensure that all _links use a treeset so ordering is consistent

A similar issue is with the 'results' array.  The ordering change
between each GET request.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by tsodring** [comment]
All HashSets have been replaced with a TreeSet and a comparable added to the base class of the entities. This should solve this issue.
